Convert to swift 5 - automatic part
VivyTeam/krypt-ios pull request #34
Opened 2019-10-17 13:28 UTC by NikolaMatijevic1

Changes in .project file and scheme

2019-10-18 09:48 UTC, markotect requested changes

2019-10-18 09:48 UTC, thehungrydev commented on Example/Tests/KeyTests.swift
> +    let publicKeyPEM = ((try? publicKey?.convertedToPEM()) as String??)
This one seems odd, does it really need double parentheses?

2019-10-18 09:48 UTC, thehungrydev commented on Krypt/Source/AES256.swift
> +        SecRandomCopyBytes(kSecRandomDefault, count, (ptr.baseAddress?.assumingMemoryBound(to: UnsafeRawBufferPointer.self))!)
Should avoid force unwrapping. 

Also I see that this function is pretty much a duplicate of the one in `MedStrickerEncryptionTests`. Maybe we could extract this to a place where they can be reused.

2019-10-18 09:48 UTC, thehungrydev commented on Example/Tests/MedStickerEncryptionTests.swift
> +      guard let pointer = ptr.baseAddress?.assumingMemoryBound(to: UnsafeRawBufferPointer.self) else { return }
I'm seeing a potential issue where we just return and don't generate random bytes, could be quite dangerous.

2019-10-18 09:48 UTC, thehungrydev commented on Krypt/Source/MedStickerEncryption.swift
> +    let combinedData = Data( combinedBytes)
SwiftFormat not running

2019-10-18 09:48 UTC, thehungrydev commented on Krypt/Source/SHA256.swift
> +        guard let pointer = ptr.baseAddress?.assumingMemoryBound(to: UnsafeRawBufferPointer.self ) else { return }
This one also seems to return just bytes of 0 instead of the hash in case of failed pointer conversion.

2019-10-21 09:14 UTC, markotect requested changes

2019-10-21 09:14 UTC, thehungrydev commented on Example/Tests/MedStickerEncryptionTests.swift
> +    let signature = MedStickerEncryption.accessSignature(attr: cipherAttr, salt: salt)!
Should keep consistent probably with where you force unwrap. e.g. test below.

2019-10-22 09:35 UTC, markotect approved these changes

2019-10-22 09:36 UTC, merged